In [2]:
import numpy as np
m_04 = np.array([1,3,5,7,9,11])
print(m_04)

[ 1  3  5  7  9 11]


In [ ]:
m_04.ndim

1

In [ ]:
m_04.shape

(6,)

In [ ]:
e_04 = np.array([[2,4,6,8],[10,4,6,8]])
print(e_04)

[[ 2  4  6  8]
 [10  4  6  8]]


In [ ]:
e_04.ndim


2

In [ ]:
e_04.shape

(2, 4)

In [ ]:
i_04 = np.array([[[1,3,5,7],[9,11,13,15]],
                 [[2,4,6,8],[10,12,14,16]],
                 [[1,2,3,4],[5,6,7,8]]])
print(i_04)

[[[ 1  3  5  7]
  [ 9 11 13 15]]

 [[ 2  4  6  8]
  [10 12 14 16]]

 [[ 1  2  3  4]
  [ 5  6  7  8]]]


In [ ]:
i_04.ndim

3

In [ ]:
i_04.shape

(3, 2, 4)

In [ ]:
a_04 = np.array([[-1,-2,-3,-4],[-3,-5,-7,-9],[-5,-6,-7,-8]])
print(a_04)

[[-1 -2 -3 -4]
 [-3 -5 -7 -9]
 [-5 -6 -7 -8]]


In [ ]:
a_04[0,3]

-4

In [ ]:
a_04[2,:]

array([-5, -6, -7, -8])

In [ ]:
a_04[:,1]

array([-2, -5, -6])

In [ ]:
a_04[0,1:3]

array([-2, -3])

In [ ]:
a_04[0,0:3:2]

array([-1, -3])

In [ ]:
a_04[0,2] = -11
print(a_04)

[[ -1  -2 -11  -4]
 [ -3  -5  -7  -9]
 [ -5  -6  -7  -8]]


In [ ]:
a_04[2,3] = -27
print(a_04)

[[ -1  -2 -11  -4]
 [ -3  -5  -7  -9]
 [ -5  -6  -7 -27]]


In [ ]:
np.ones((3,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((6,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.ones((2,8,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [ ]:
np.random.rand(5,3)

array([[0.83292017, 0.63338864, 0.52029461],
       [0.38821489, 0.38024245, 0.96261601],
       [0.19235785, 0.80856694, 0.97850886],
       [0.87983902, 0.45901216, 0.19016257],
       [0.32764847, 0.79129936, 0.45871739]])

In [ ]:
np.random.randint(1,10,size=(2,5))

array([[2, 4, 5, 9, 5],
       [9, 5, 3, 9, 5]])

In [ ]:
n_04 = np.zeros((15,15))
print(n_04)
print('==============================')
d_04 = np.identity(15)
print(d_04)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0

In [ ]:
h_04 = 14*d_04
print(h_04)

[[14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 14.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 14.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 14.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.]]


In [ ]:
w_04 = np.ones((13,13))
print(w_04)
print('===============================')
g_04 = np.identity(13)*13
print(g_04)
print('===============================')
c_04 = w_04+g_04
print(c_04)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 13.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 13.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 13.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 13.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.

In [ ]:
c_04

array([[14.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1., 14.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., 14.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 14.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 14.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 14.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., 14.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1., 14.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 14.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 14.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 14.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 14.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 14.]])

In [ ]:
h_04[1:-1,1:-1] = c_04
print(h_04)

[[14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 14.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1. 14.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1. 14.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1. 14.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1. 14.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1. 14.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1. 14.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1. 14.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1. 14.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1. 14.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 14.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 14.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 14.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.]]


In [ ]:
i_04 = np.identity(11)*14
h_04[2:-2,2:-2] = i_04
print(h_04)

[[14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 14.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0. 14.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0. 14.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0. 14.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0. 14.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0. 14.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0. 14.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0. 14.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 14.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.]]


In [ ]:
g_04 = np.ones((9,9))*9
k_04 = np.identity(9) * 12
m_04 = g_04 + k_04
print(m_04)

[[21.  9.  9.  9.  9.  9.  9.  9.  9.]
 [ 9. 21.  9.  9.  9.  9.  9.  9.  9.]
 [ 9.  9. 21.  9.  9.  9.  9.  9.  9.]
 [ 9.  9.  9. 21.  9.  9.  9.  9.  9.]
 [ 9.  9.  9.  9. 21.  9.  9.  9.  9.]
 [ 9.  9.  9.  9.  9. 21.  9.  9.  9.]
 [ 9.  9.  9.  9.  9.  9. 21.  9.  9.]
 [ 9.  9.  9.  9.  9.  9.  9. 21.  9.]
 [ 9.  9.  9.  9.  9.  9.  9.  9. 21.]]


In [ ]:
h_04[3:-3,3:-3] = m_04
print(h_04)

[[14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 14.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0. 21.  9.  9.  9.  9.  9.  9.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9. 21.  9.  9.  9.  9.  9.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9. 21.  9.  9.  9.  9.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9.  9. 21.  9.  9.  9.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9.  9.  9. 21.  9.  9.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9.  9.  9.  9. 21.  9.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9.  9.  9.  9.  9. 21.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9.  9.  9.  9.  9.  9. 21.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9.  9.  9.  9.  9.  9.  9. 21.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 14.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.]]


In [ ]:
p_04 = np.identity(7)*9
h_04[4:-4,4:-4] = p_04
print(h_04)

[[14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 14.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0. 21.  9.  9.  9.  9.  9.  9.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9.  0.  0.  0.  0.  0.  0.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  0.  9.  0.  0.  0.  0.  0.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  0.  0.  9.  0.  0.  0.  0.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  0.  0.  0.  9.  0.  0.  0.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  0.  0.  0.  0.  9.  0.  0.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  0.  0.  0.  0.  0.  9.  0.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  0.  0.  0.  0.  0.  0.  9.  9.  0.  1.  0.]
 [ 0.  1.  0.  9.  9.  9.  9.  9.  9.  9.  9. 21.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 14.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 14.]]


In [ ]:
p_04 = np.array([-2,0,5,8,-5])
print(p_04)
print('===============================')
q_04 = p_04
print(q_04)
print('===============================')
q_04[2] = -6
print(q_04)
print('===============================')
print(p_04)

[-2  0  5  8 -5]
[-2  0  5  8 -5]
[-2  0 -6  8 -5]
[-2  0 -6  8 -5]


In [ ]:
x_04 = np.array([-2,-8,5,9,0])
print(x_04)
print('===============================')
y_04 = x_04.copy()
print(y_04)
print('===============================')
y_04[3] = 17
print(y_04)
print('===============================')
print(x_04)

[-2 -8  5  9  0]
[-2 -8  5  9  0]
[-2 -8  5 17  0]
[-2 -8  5  9  0]


In [ ]:
q_04 = np.array([2,4,6,8,10])
print(q_04)
p_04 = np.array([1,3,5,7,9])
print(p_04)

[ 2  4  6  8 10]
[1 3 5 7 9]


In [ ]:
q_04+p_04


array([ 3,  7, 11, 15, 19])

In [ ]:
q_04-p_04

array([1, 1, 1, 1, 1])

In [ ]:
q_04*p_04

array([ 2, 12, 30, 56, 90])

In [ ]:
q_04/p_04

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111])

In [ ]:
p_04**q_04

array([         1,         81,      15625,    5764801, 3486784401])

In [ ]:
np.cos(q_04)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003, -0.83907153])

In [ ]:
np.cos(p_04)

array([ 0.54030231, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026])

In [ ]:
np.sin(q_04)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825, -0.54402111])

In [ ]:
np.cosh(q_04)

array([3.76219569e+00, 2.73082328e+01, 2.01715636e+02, 1.49047916e+03,
       1.10132329e+04])

In [ ]:
np.tanh(q_04)

array([0.96402758, 0.9993293 , 0.99998771, 0.99999977, 1.        ])

In [ ]:
np.sqrt(q_04)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [4]:
f_04 = np.array([[9,10,11,12],[13,14,15,16]])
print(f_04)
g_04 = np.array([[1,2,3,4],[5,6,7,8]])
print(g_04)

[[ 9 10 11 12]
 [13 14 15 16]]
[[1 2 3 4]
 [5 6 7 8]]


In [6]:
l_04 = f_04*g_04
print(l_04)

[[  9  20  33  48]
 [ 65  84 105 128]]


In [7]:
s_04 = np.array([[-1,-2],[-3,-4],[-5,-6],[-7,-8]])
print(s_04)

[[-1 -2]
 [-3 -4]
 [-5 -6]
 [-7 -8]]


In [8]:
t_04 = np.matmul(f_04,s_04)
print(t_04)

[[-178 -220]
 [-242 -300]]


In [4]:
b_04 = np.array([[1,3,5,-7],
                 [0,3,-5,7],
                 [16,0,-9,7]])
print(b_04)

[[ 1  3  5 -7]
 [ 0  3 -5  7]
 [16  0 -9  7]]


In [5]:
c_04 = np.min(b_04)
print(c_04)

-9


In [7]:
e_04 = np.min(b_04,axis=0)
print(e_04)
print('===============================')
i_04 = np.min(b_04,axis=1)
print(i_04)
print('===============================')

[ 0  0 -9 -7]
[-7 -5 -9]


In [9]:
u_04 = np.max(b_04)
print(u_04)
print('===============================')
y_04 = np.max(b_04,axis=0)
print(y_04)
print('===============================')
r_04 = np.max(b_04,axis=1)
print(r_04)

16
[16  3  5  7]
[ 5  7 16]


In [10]:
a_04 = np.sum(b_04)
print(a_04)
print('===============================')
d_04 = np.sum(b_04,axis=0)
print(d_04)
print('===============================')
p_04 = np.sum(b_04,axis=1)
print(p_04)

21
[17  6 -9  7]
[ 2  5 14]
